# Generated by Django 3.2.8 on 2021-10-24 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=140)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=140)),
                ('module', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.module')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=140)),
                ('url', models.URLField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submodule', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.submodule')),
            ],
        ),
    ]
