# Generated by Django 3.2.8 on 2021-10-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_module_resource_submodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='submodule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.submodule'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='description',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.RemoveField(
            model_name='submodule',
            name='module',
        ),
        migrations.AddField(
            model_name='submodule',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.module'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='title',
            field=models.CharField(default='', max_length=140),
        ),
    ]
