# Generated by Django 3.2.8 on 2021-10-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_module_resource_submodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.module'),
        ),
    ]
