# Generated by Django 3.2.8 on 2021-10-24 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_submodule_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='submodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_submodule', to='user.submodule'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_module', to='user.module'),
        ),
    ]
