# Generated by Django 3.2.8 on 2021-10-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_module_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at']},
        ),
    ]
