# Generated by Django 3.2.8 on 2021-10-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211024_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
    ]
