# Generated by Django 3.2.8 on 2021-10-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_module_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='public',
        ),
    ]
