# Generated by Django 3.2.8 on 2021-10-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211024_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='Title',
            new_name='title',
        ),
    ]
